package com.abc.abc.model;

public class GogoupCourseWithBLOBs extends GogoupCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.coach_desc
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String coachDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.call_center
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String callCenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.data_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String dataIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.wap_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String wapIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.intro
     *
     * @return the value of gogoup_course.intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.intro
     *
     * @param intro the value for gogoup_course.intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.coach_desc
     *
     * @return the value of gogoup_course.coach_desc
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getCoachDesc() {
        return coachDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.coach_desc
     *
     * @param coachDesc the value for gogoup_course.coach_desc
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCoachDesc(String coachDesc) {
        this.coachDesc = coachDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.call_center
     *
     * @return the value of gogoup_course.call_center
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getCallCenter() {
        return callCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.call_center
     *
     * @param callCenter the value for gogoup_course.call_center
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCallCenter(String callCenter) {
        this.callCenter = callCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.data_intro
     *
     * @return the value of gogoup_course.data_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getDataIntro() {
        return dataIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.data_intro
     *
     * @param dataIntro the value for gogoup_course.data_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDataIntro(String dataIntro) {
        this.dataIntro = dataIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.wap_intro
     *
     * @return the value of gogoup_course.wap_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getWapIntro() {
        return wapIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.wap_intro
     *
     * @param wapIntro the value for gogoup_course.wap_intro
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setWapIntro(String wapIntro) {
        this.wapIntro = wapIntro;
    }
}