package com.abc.abc.model;

import java.util.Date;

public class GogoupCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.description
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.bg_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String bgImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.bg_color
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String bgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.data_pack_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Double dataPackPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.hw_com_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Double hwComPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.total_duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer totalDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.status
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.teach_name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String teachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.teac_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long teacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.teac_id_two
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long teacIdTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.discount_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date discountTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.cate_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.user_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.edit_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long editId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.create_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.update_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.deleted
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.data_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String dataImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.ori_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Double oriPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.discount
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.coach
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer coach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.coach_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Double coachPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.ad_video_url
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String adVideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.intro_coler
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String introColer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.diff_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Long diffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.app_cover
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String appCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.validity
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer validity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.begin_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.end_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.star_level
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer starLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.tags
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.stop_sale
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer stopSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.is_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.keywords
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.applicable
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String applicable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.listing_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date listingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.offline
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer offline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.series
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer series;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.top_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Date topTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.is_end
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.marketing_type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Integer marketingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.qq_group
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String qqGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.qq_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String qqExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.wechat_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String wechatExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.qrcode
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.is_modul
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Byte isModul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.train_mark
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Byte trainMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.app_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private Byte appShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.wechat
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gogoup_course.recommend
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    private String recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.id
     *
     * @return the value of gogoup_course.id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.id
     *
     * @param id the value for gogoup_course.id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.name
     *
     * @return the value of gogoup_course.name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.name
     *
     * @param name the value for gogoup_course.name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.description
     *
     * @return the value of gogoup_course.description
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.description
     *
     * @param description the value for gogoup_course.description
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.image
     *
     * @return the value of gogoup_course.image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.image
     *
     * @param image the value for gogoup_course.image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.bg_image
     *
     * @return the value of gogoup_course.bg_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getBgImage() {
        return bgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.bg_image
     *
     * @param bgImage the value for gogoup_course.bg_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setBgImage(String bgImage) {
        this.bgImage = bgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.bg_color
     *
     * @return the value of gogoup_course.bg_color
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.bg_color
     *
     * @param bgColor the value for gogoup_course.bg_color
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.data_pack_price
     *
     * @return the value of gogoup_course.data_pack_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Double getDataPackPrice() {
        return dataPackPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.data_pack_price
     *
     * @param dataPackPrice the value for gogoup_course.data_pack_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDataPackPrice(Double dataPackPrice) {
        this.dataPackPrice = dataPackPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.hw_com_price
     *
     * @return the value of gogoup_course.hw_com_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Double getHwComPrice() {
        return hwComPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.hw_com_price
     *
     * @param hwComPrice the value for gogoup_course.hw_com_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setHwComPrice(Double hwComPrice) {
        this.hwComPrice = hwComPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.total_duration
     *
     * @return the value of gogoup_course.total_duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getTotalDuration() {
        return totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.total_duration
     *
     * @param totalDuration the value for gogoup_course.total_duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTotalDuration(Integer totalDuration) {
        this.totalDuration = totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.price
     *
     * @return the value of gogoup_course.price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.price
     *
     * @param price the value for gogoup_course.price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.status
     *
     * @return the value of gogoup_course.status
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.status
     *
     * @param status the value for gogoup_course.status
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.teach_name
     *
     * @return the value of gogoup_course.teach_name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getTeachName() {
        return teachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.teach_name
     *
     * @param teachName the value for gogoup_course.teach_name
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTeachName(String teachName) {
        this.teachName = teachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.teac_id
     *
     * @return the value of gogoup_course.teac_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.teac_id
     *
     * @param teacId the value for gogoup_course.teac_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTeacId(Long teacId) {
        this.teacId = teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.teac_id_two
     *
     * @return the value of gogoup_course.teac_id_two
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getTeacIdTwo() {
        return teacIdTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.teac_id_two
     *
     * @param teacIdTwo the value for gogoup_course.teac_id_two
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTeacIdTwo(Long teacIdTwo) {
        this.teacIdTwo = teacIdTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.discount_time
     *
     * @return the value of gogoup_course.discount_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getDiscountTime() {
        return discountTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.discount_time
     *
     * @param discountTime the value for gogoup_course.discount_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDiscountTime(Date discountTime) {
        this.discountTime = discountTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.cate_id
     *
     * @return the value of gogoup_course.cate_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.cate_id
     *
     * @param cateId the value for gogoup_course.cate_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCateId(Long cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.user_id
     *
     * @return the value of gogoup_course.user_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.user_id
     *
     * @param userId the value for gogoup_course.user_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.edit_id
     *
     * @return the value of gogoup_course.edit_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getEditId() {
        return editId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.edit_id
     *
     * @param editId the value for gogoup_course.edit_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setEditId(Long editId) {
        this.editId = editId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.create_time
     *
     * @return the value of gogoup_course.create_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.create_time
     *
     * @param createTime the value for gogoup_course.create_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.update_time
     *
     * @return the value of gogoup_course.update_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.update_time
     *
     * @param updateTime the value for gogoup_course.update_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.deleted
     *
     * @return the value of gogoup_course.deleted
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.deleted
     *
     * @param deleted the value for gogoup_course.deleted
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.data_image
     *
     * @return the value of gogoup_course.data_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getDataImage() {
        return dataImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.data_image
     *
     * @param dataImage the value for gogoup_course.data_image
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDataImage(String dataImage) {
        this.dataImage = dataImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.ori_price
     *
     * @return the value of gogoup_course.ori_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Double getOriPrice() {
        return oriPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.ori_price
     *
     * @param oriPrice the value for gogoup_course.ori_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setOriPrice(Double oriPrice) {
        this.oriPrice = oriPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.discount
     *
     * @return the value of gogoup_course.discount
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.discount
     *
     * @param discount the value for gogoup_course.discount
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.coach
     *
     * @return the value of gogoup_course.coach
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getCoach() {
        return coach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.coach
     *
     * @param coach the value for gogoup_course.coach
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCoach(Integer coach) {
        this.coach = coach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.coach_price
     *
     * @return the value of gogoup_course.coach_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Double getCoachPrice() {
        return coachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.coach_price
     *
     * @param coachPrice the value for gogoup_course.coach_price
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setCoachPrice(Double coachPrice) {
        this.coachPrice = coachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.ad_video_url
     *
     * @return the value of gogoup_course.ad_video_url
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getAdVideoUrl() {
        return adVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.ad_video_url
     *
     * @param adVideoUrl the value for gogoup_course.ad_video_url
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setAdVideoUrl(String adVideoUrl) {
        this.adVideoUrl = adVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.intro_coler
     *
     * @return the value of gogoup_course.intro_coler
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getIntroColer() {
        return introColer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.intro_coler
     *
     * @param introColer the value for gogoup_course.intro_coler
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setIntroColer(String introColer) {
        this.introColer = introColer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.type
     *
     * @return the value of gogoup_course.type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.type
     *
     * @param type the value for gogoup_course.type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.diff_id
     *
     * @return the value of gogoup_course.diff_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Long getDiffId() {
        return diffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.diff_id
     *
     * @param diffId the value for gogoup_course.diff_id
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDiffId(Long diffId) {
        this.diffId = diffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.app_cover
     *
     * @return the value of gogoup_course.app_cover
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getAppCover() {
        return appCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.app_cover
     *
     * @param appCover the value for gogoup_course.app_cover
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setAppCover(String appCover) {
        this.appCover = appCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.validity
     *
     * @return the value of gogoup_course.validity
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.validity
     *
     * @param validity the value for gogoup_course.validity
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.begin_time
     *
     * @return the value of gogoup_course.begin_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.begin_time
     *
     * @param beginTime the value for gogoup_course.begin_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.end_time
     *
     * @return the value of gogoup_course.end_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.end_time
     *
     * @param endTime the value for gogoup_course.end_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.duration
     *
     * @return the value of gogoup_course.duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.duration
     *
     * @param duration the value for gogoup_course.duration
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.star_level
     *
     * @return the value of gogoup_course.star_level
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.star_level
     *
     * @param starLevel the value for gogoup_course.star_level
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setStarLevel(Integer starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.tags
     *
     * @return the value of gogoup_course.tags
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.tags
     *
     * @param tags the value for gogoup_course.tags
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.stop_sale
     *
     * @return the value of gogoup_course.stop_sale
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getStopSale() {
        return stopSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.stop_sale
     *
     * @param stopSale the value for gogoup_course.stop_sale
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setStopSale(Integer stopSale) {
        this.stopSale = stopSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.is_show
     *
     * @return the value of gogoup_course.is_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.is_show
     *
     * @param isShow the value for gogoup_course.is_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.keywords
     *
     * @return the value of gogoup_course.keywords
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.keywords
     *
     * @param keywords the value for gogoup_course.keywords
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.applicable
     *
     * @return the value of gogoup_course.applicable
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.applicable
     *
     * @param applicable the value for gogoup_course.applicable
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setApplicable(String applicable) {
        this.applicable = applicable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.listing_time
     *
     * @return the value of gogoup_course.listing_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getListingTime() {
        return listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.listing_time
     *
     * @param listingTime the value for gogoup_course.listing_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setListingTime(Date listingTime) {
        this.listingTime = listingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.offline
     *
     * @return the value of gogoup_course.offline
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getOffline() {
        return offline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.offline
     *
     * @param offline the value for gogoup_course.offline
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setOffline(Integer offline) {
        this.offline = offline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.series
     *
     * @return the value of gogoup_course.series
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.series
     *
     * @param series the value for gogoup_course.series
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setSeries(Integer series) {
        this.series = series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.top_time
     *
     * @return the value of gogoup_course.top_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Date getTopTime() {
        return topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.top_time
     *
     * @param topTime the value for gogoup_course.top_time
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTopTime(Date topTime) {
        this.topTime = topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.is_end
     *
     * @return the value of gogoup_course.is_end
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.is_end
     *
     * @param isEnd the value for gogoup_course.is_end
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.marketing_type
     *
     * @return the value of gogoup_course.marketing_type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Integer getMarketingType() {
        return marketingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.marketing_type
     *
     * @param marketingType the value for gogoup_course.marketing_type
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setMarketingType(Integer marketingType) {
        this.marketingType = marketingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.qq_group
     *
     * @return the value of gogoup_course.qq_group
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getQqGroup() {
        return qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.qq_group
     *
     * @param qqGroup the value for gogoup_course.qq_group
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setQqGroup(String qqGroup) {
        this.qqGroup = qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.qq_explain
     *
     * @return the value of gogoup_course.qq_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getQqExplain() {
        return qqExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.qq_explain
     *
     * @param qqExplain the value for gogoup_course.qq_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setQqExplain(String qqExplain) {
        this.qqExplain = qqExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.wechat_explain
     *
     * @return the value of gogoup_course.wechat_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getWechatExplain() {
        return wechatExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.wechat_explain
     *
     * @param wechatExplain the value for gogoup_course.wechat_explain
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setWechatExplain(String wechatExplain) {
        this.wechatExplain = wechatExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.qrcode
     *
     * @return the value of gogoup_course.qrcode
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.qrcode
     *
     * @param qrcode the value for gogoup_course.qrcode
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.is_modul
     *
     * @return the value of gogoup_course.is_modul
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Byte getIsModul() {
        return isModul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.is_modul
     *
     * @param isModul the value for gogoup_course.is_modul
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setIsModul(Byte isModul) {
        this.isModul = isModul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.train_mark
     *
     * @return the value of gogoup_course.train_mark
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Byte getTrainMark() {
        return trainMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.train_mark
     *
     * @param trainMark the value for gogoup_course.train_mark
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setTrainMark(Byte trainMark) {
        this.trainMark = trainMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.app_show
     *
     * @return the value of gogoup_course.app_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public Byte getAppShow() {
        return appShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.app_show
     *
     * @param appShow the value for gogoup_course.app_show
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setAppShow(Byte appShow) {
        this.appShow = appShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.wechat
     *
     * @return the value of gogoup_course.wechat
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.wechat
     *
     * @param wechat the value for gogoup_course.wechat
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gogoup_course.recommend
     *
     * @return the value of gogoup_course.recommend
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gogoup_course.recommend
     *
     * @param recommend the value for gogoup_course.recommend
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }
}