package com.abc.abc.dao.persistence;

import com.abc.abc.model.GogoupCourse;
import com.abc.abc.model.GogoupCourseExample;
import com.abc.abc.model.GogoupCourseWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GogoupCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int countByExample(GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int deleteByExample(GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int insert(GogoupCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int insertSelective(GogoupCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    List<GogoupCourseWithBLOBs> selectByExampleWithBLOBs(GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    List<GogoupCourse> selectByExample(GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    GogoupCourseWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") GogoupCourseWithBLOBs record, @Param("example") GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") GogoupCourseWithBLOBs record, @Param("example") GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByExample(@Param("record") GogoupCourse record, @Param("example") GogoupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByPrimaryKeySelective(GogoupCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(GogoupCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gogoup_course
     *
     * @mbggenerated Fri Jun 14 18:22:52 CST 2019
     */
    int updateByPrimaryKey(GogoupCourse record);
}